stages:
  features:
    desc: "Фичи для прогноза заказов такси"
    cmd: powershell -Command "if (-Not (Test-Path db_destination/taxi_features.csv)) { '' | Out-File db_destination/taxi_features.csv }"
    deps:
      - db_source/taxi.csv
    outs:
      - db_destination/taxi_features.csv
